// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://udkxqhhrkqnhwabmjtzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVka3hxaGhya3FuaHdhYm1qdHp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2MDA3NTMsImV4cCI6MjA2MTE3Njc1M30.169QzMEiF3zyq_X_-ctTXNHP6R-kC_ni05PlofPv2gE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);